---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qmpiyirj0j0o/public_html/
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/css
    
